import { Metadata } from 'next';
import { Card, CardContent } from '@/components/ui/card';

export const metadata: Metadata = {
  title: 'Privacy Policy | Clockivo',
  description: 'Read the Clockivo Privacy Policy to understand how we protect your data, use local storage, and implement analytics.',
  alternates: {
    canonical: 'https://www.clockivo.com/privacy-policy'
  }
};

export default function PrivacyPolicyPage() {
  return (
    <div className="container max-w-4xl py-12 px-4 sm:px-6 lg:px-8 mx-auto">
      <div className="space-y-8">
        <div className="text-center space-y-4">
          <h1 className="text-4xl md:text-5xl font-extrabold tracking-tight bg-gradient-to-r from-primary to-primary/50 bg-clip-text text-transparent">
            Privacy Policy
          </h1>
          <p className="text-muted-foreground">
            Last Updated: {new Date().toLocaleDateString('en-US', { month: 'long', day: 'numeric', year: 'numeric' })}
          </p>
        </div>

        <Card className="border-border/50 bg-card/50 backdrop-blur-sm">
          <CardContent className="p-8 prose prose-invert max-w-none">
            <h3>1. Introduction</h3>
            <p>
              Welcome to Clockivo ("we", "our", or "us"). We respect your privacy and are committed to protecting it through our compliance with this policy. This Privacy Policy describes the types of information we may collect from you or that you may provide when you visit the website <a href="https://www.clockivo.com" className="text-primary">www.clockivo.com</a> (our "Website") and our practices for collecting, using, maintaining, protecting, and disclosing that information.
            </p>

            <h3>2. Information We Do NOT Collect</h3>
            <p>
              We pride ourselves on being a privacy-first utility. <strong>We do not collect, store, or transmit your personal alarm schedules, timer settings, or stopwatch history to our servers.</strong> All of this data is strictly saved locally on your device using your browser's <code>localStorage</code> API. If you clear your browser cache, your saved alarms and timers will be permanently deleted.
            </p>

            <h3>3. Information We Collect Through Automatic Data Collection Technologies</h3>
            <p>
              As you navigate through and interact with our Website, we may use automatic data collection technologies (specifically Google Analytics) to collect certain information about your equipment, browsing actions, and patterns, including:
            </p>
            <ul>
              <li>Details of your visits to our Website, including traffic data, location data (at a city/country level), logs, and other communication data and the resources that you access and use on the Website.</li>
              <li>Information about your computer and internet connection, including your IP address, operating system, and browser type.</li>
            </ul>

            <h3>4. Google Analytics & Cookies</h3>
            <p>
              We use <strong>Google Analytics</strong> to understand how users engage with our Website. Google Analytics uses "cookies", which are text files placed on your computer, to help the website analyze how users use the site. The information generated by the cookie about your use of the website (including your IP address) will be transmitted to and stored by Google on servers in the United States.
            </p>
            <p>
              Google uses this information to evaluate your use of the website, compile reports on website activity, and provide other services relating to website activity and internet usage. You may refuse the use of cookies by selecting the appropriate settings on your browser, however, please note that if you do this you may not be able to use the full functionality of this website.
            </p>
            <p>
              For more information on how Google collects and processes data, please visit <a href="https://policies.google.com/technologies/partner-sites" target="_blank" rel="noopener noreferrer" className="text-primary hover:underline">Google's Privacy & Terms</a>.
            </p>

            <h3>5. Third-Party Advertisements</h3>
            <p>
              We may use third-party advertising companies to serve ads when you visit our Website. These companies may use aggregated information (not including your name, address, email address, or telephone number) about your visits to this and other websites in order to provide advertisements about goods and services of interest to you.
            </p>

            <h3>6. Children Under the Age of 13</h3>
            <p>
              Our Website is not intended for children under 13 years of age. No one under age 13 may provide any information to or on the Website. We do not knowingly collect personal information from children under 13.
            </p>

            <h3>7. Changes to Our Privacy Policy</h3>
            <p>
              It is our policy to post any changes we make to our privacy policy on this page. If we make material changes to how we treat our users' personal information, we will notify you through a notice on the Website home page. The date the privacy policy was last revised is identified at the top of the page.
            </p>

            <h3>8. Contact Information</h3>
            <p>
              To ask questions or comment about this privacy policy and our privacy practices, contact us via email at <strong>privacy@clockivo.com</strong>.
            </p>
          </CardContent>
        </Card>
      </div>
    </div>
  );
}
